project:
  type: website
  output-dir: docs

website:
  title: "MLBlog"
  repo-url: https://github.com/tpriya14/MLBlog/blob/gh-pages/
  repo-actions: [source]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tpriya14
      - icon: twitter
        href: https://twitter.com/tspriya14
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


