project:
  type: website
  output-dir: docs

website:
  title: "MLBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tpriya14/MLBlog
      - icon: twitter
        href: https://twitter.com/tspriya14
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


